### ISSUE TITLE
any installation manual?

### ISSUE THREAD

**Issue by cookins** [Kastuk/Stationeers-Creative-Freedom#1]
hey
im not exactly programmer, but where i need to use this CSharp files? i just need freedom with build placement. any installation manual?

**Comment by Kastuk** [comment]
Okay, I did publish release for first time, but it still unfinished.
https://github.com/Kastuk/Stationeers-Creative-Freedom/releases/tag/v0.5

Installing like any proper bepinex mod, like this one:
https://github.com/ilodev/StationeersPerishableItems

Download last stable BepInEx release:
https://github.com/BepInEx/BepInEx/releases
Unpack it into SteamLibrary\steamapps\common\Stationeers folder
Run Stationeers once, so BepInEx will be installed.
Place dll file of the mod into Stationeers\BepInEx\plugins

**Comment by cookins** [comment]
that helped. ty
